baseURL = "https://ngere83.github.io/"
languageCode = "ja-jp"
title = "私はとても焦っている"
theme = "PaperMod"

[params]
defaultTheme = "light"
DateFormat = "2006-01-02 15:04"
mainSections = ["shorts", "notes", "tech", "food", "art", "games"]

[[menu.main]]
name = "HOME"
url = "/"
weight = 1

[[menu.main]]
name = "Post"
url = "/shorts/"
weight = 5

[[menu.main]]
name = "Notes"
url = "/notes/"
weight = 10

[[menu.main]]
name = "Tech"
url = "/tech/"
weight = 20

[[menu.main]]
name = "Food"
url = "/food/"
weight = 30

[[menu.main]]
name = "Art"
url = "/art/"
weight = 40

[[menu.main]]
name = "Games"
url = "/games/"
weight = 50

[[menu.main]]
name = "About"
url = "/about/"
weight = 60

[params.assets]
favicon = "/images/とりアイコン.png"
favicon16x16 = "/images/とりアイコン.png"
favicon32x32 = "/images/とりアイコン.png"
apple_touch_icon = "/images/とりアイコン.png"

[services]
  [services.googleAnalytics]
    id = "G-T2MYDJ6PLG"
