baseURL = "https://ngere83.github.io/"
languageCode = "ja-jp"
title = "私はとても焦っている"
theme = "PaperMod"

[params]
mainSections = ["shorts", "notes", "tech", "projects", "art", "games"]

[[menu.main]]
name = "HOME"
url = "/"
weight = 1

[[menu.main]]
name = "Post"
url = "/shorts/"
weight = 5

[[menu.main]]
name = "Notes"
url = "/notes/"
weight = 10

[[menu.main]]
name = "Tech"
url = "/tech/"
weight = 20

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 30

[[menu.main]]
name = "Art"
url = "/art/"
weight = 40

[[menu.main]]
name = "Games"
url = "/games/"
weight = 50

[[menu.main]]
name = "About"
url = "/about/"
weight = 60

[params.assets]
favicon = "/images/もちアイコン.png"
favicon16x16 = "/images/もちアイコン.png"
favicon32x32 = "/images/もちアイコン.png"
apple_touch_icon = "/images/もちアイコン.png"
