#requires -Version 7.0
[CmdletBinding()]
param([Parameter(Mandatory)][string]$Path)
$ErrorActionPreference = 'Stop'
. "$PSScriptRoot/trash-common.ps1"

# Relative paths follow the caller's working directory.
$source = Get-PostPath $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($Path)
$item = Assert-PostItem $source
Assert-PlainPath $TrashRoot
$id = (Get-Date -Format 'yyyyMMdd-HHmmss') + '-' + [guid]::NewGuid().ToString('N')
$directory = Join-Path $TrashRoot $id
$payload = Join-Path $directory 'payload'
$title = $item.BaseName
$markdown = if ($item.PSIsContainer) { Join-Path $source 'index.md' } else { $source }
$text = Get-Content -LiteralPath $markdown -Raw
# Best-effort title extraction for the TOML generated by the posting commands.
if ($text -match '(?ms)\A\+\+\+\r?\n(.*?)\r?\n\+\+\+') {
    $frontMatter = $Matches[1]
    if ($frontMatter -match '(?m)^title\s*=\s*("(?:\\.|[^"\\])*"|''[^'']*'')\s*$') {
        $literal = $Matches[1]
        try { $title = if ($literal.StartsWith('"')) { ConvertFrom-Json $literal } else { $literal.Substring(1, $literal.Length - 2) } } catch { }
    }
}
$metadata = [pscustomobject]@{
    Id = $id
    DeletedAt = [DateTimeOffset]::Now.ToString('o')
    OriginalPath = [IO.Path]::GetRelativePath($TrashSiteRoot, $source).Replace('\', '/')
    Kind = $(if ($item.PSIsContainer) { 'directory' } else { 'file' })
    Title = $title
}
New-Item -ItemType Directory -Path $payload | Out-Null
$metadata | ConvertTo-Json | Set-Content -LiteralPath (Join-Path $directory 'metadata.json') -Encoding utf8
# No force, overwrite or Git operations. Metadata exists before the move.
Move-Item -LiteralPath $source -Destination (Join-Path $payload $item.Name)
Write-Output $metadata
